function prop=greenProps()
prop = {...
    'Color', [1 0 0],...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',5,...
    'MarkerFaceColor',[0.39,0.83,0.07],...
    'MarkerEdgeColor',[0 0 0],...
};
end