function props = probeProps()
props = {...
    'Color', [1 0 0],...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',3,...
    'MarkerFaceColor', [0.49,0.18,0.56],...
    'MarkerEdgeColor',[0 0 0],...
};