% Return unfeasible point styling.

% Copyright (C) 2020 Timon Viola
function prop = unfeasibleProps()
prop = {...
    'Color', [1 0 0],...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',5,...
    'MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor',[0 0 0],...
};